### ISSUE TITLE
form data does not persist

### ISSUE THREAD

**Issue by stevenmunro** [srdjan/react-multistep#36] opened 2018-07-11 23:20 UTC
Form data does not appear to persist across 'steps', however, your gh-pages branch does. Is there a reason the state of each form field is not kept between steps in your master branch?

I am a bit confused.

**Comment by stevenmunro** [comment] 2018-07-12 23:15
The repo link is this one.

I cloned https://github.com/srdjan/react-multistep/ and ran `npm install` and `npm run build-with-webpack`
Then I opened ./example/index.html in my browser.

Form loads, however, there is no REACT tab available for my chrome react developer tools. Is there a step I am missing?

**Comment by irobalino** [comment] 2018-07-24 22:35
Hi stevenmunro. I am having the same issue as you but I don't not fully understand how you fixed it (new to React). Could you maybe shared the code to learn from it? Thanks in advance

**Comment by srdjan** [comment] 2018-08-05 17:54
closing this - this is by design... user should adopt their own state management strategy

**Closed by srdjan** 2018-08-05 17:54 UTC
