### ISSUE TITLE
Story: Deactivate the 'Next' button based on form validation

### ISSUE THREAD

**Issue by dividor** [srdjan/react-multistep#98] opened 2022-11-25 21:31 UTC
Hi @srdjan,

Fantastic component, thanks a lot!

I would like to be able to disable the 'Next' button until the user has entered all fields on a form. I have searched through previous issues related to validation, and the closest I can find is perhaps #32 , but it means modifying `MultiStep.js`.

Is there a supported way please to control visibility of the 'Next' button based on activity in the child form?

Thanks.

**Comment by srdjan** [comment] 2022-11-27 01:41
yes, #32 is the proposed solution where child form signals (invokes callback) when it is 'valid' to proceed. I suppose alternative would be to try pass prop (button visibility) to child component? Is that what you had in mind?

**Comment by dividor** [comment] 2022-11-27 03:14
I like the idea of the child component being able to control visibility via
caller prop (some folks might want to show the button but have it disabled
too perhaps). Then people can implement whatever logic they want in the
child form.

**Comment by srdjan** [comment] 2022-11-27 16:47
will give it a try...
Also, will merge this issue (as alternative solution) with the original #32  and close.
Plan to implement it (one way or another ;) over the Holidays

**Comment by srdjan** [comment] 2022-11-27 16:49
actually, I'll keep this one as a story for this feature :)

**Comment by dividor** [comment] 2022-11-28 00:23
Awesome, thanks!

**Comment by satemafac** [comment] 2022-12-31 20:49
I am also waiting eagerly to see this feature added! This is a very great easy to implement multi-step form adding this would only make it that much better, thanks!

**Comment by DillonZip** [comment] 2023-01-21 04:01
I really need this to get addressed. Field validation is a must for my application but if I cant control what happens when the 'next' button is clicked then I'll have to find a new package, and I really don't want to do that :'(

**Comment by DillonZip** [comment] 2023-01-21 05:17
This may be a hacky solution, but it's working for me while I'm waiting for this to get address. Here's what I did:
I created a state variable for "nextStyle" and pass the setter to the component I render for each step. I default the "Next" button CSS to be greyed out and set pointerEvents: "none" so that it can't be clicked.
Then, in the 'step' component the next button is already disabled, and as the user populates the inputs I call a validation function that checks the various input fields. If any fail validation then I keep the button style as is, but if all validation is passed then I use that passed in state setter to change the style of the button, changing it back to blue and setting pointerEvents: "auto".

In the form initialization class:
```
const MyForm = () => {
  const [nextStyle, setNextStyle] = useState({
    background: "#cccccc",
    borderWidth: "0px",
    color: "#fff",
    borderRadius: "4px",
    fontSize: "14px",
    fontWeight: "600",
    padding: "12px 18px",
    pointerEvents: "none"
  });

 const steps = [
    { title: "Step 1", component: <FormStepOne setNextStyle={setNextStyle} /> },
    { title: "Step 2", component: <FormStepTwo setNextStyle={setNextStyle} /> },
    { title: "Step 3", component: <FormStepThree setNextStyle={setNextStyle} /> },
    { title: "Step 4", component: <FormStepFour setNextStyle={setNextStyle} /> },
  ];

 <MultiStep steps={steps} prevStyle={prevStyle} nextStyle={nextStyle} />
}
```

In the form component, e.g. FormStepOne:
```
const AddBankFormStepOne = ({setNextStyle}) => {
 const validateForm= (formData) => {
   <Do Validation Here>
   
   if (ValidationFailed) {
     			setNextStyle({
				background: "#cccccc",
				borderWidth: "0px",
				color: "#fff",
				borderRadius: "4px",
				fontSize: "14px",
				fontWeight: "600",
				padding: "12px 18px",
				pointerEvents: "none"
			});
   }
   else {
      setNextStyle({
				background: "#4885ed",
				borderWidth: "0px",
				color: "#fff",
				borderRadius: "4px",
				fontSize: "14px",
				fontWeight: "600",
				padding: "12px 18px",
				pointerEvents: "auto"
			});
   }
 }
}
```

Not an ideal solution. The console does throw a warning
`Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component`
But at least it got the job done for me for now. Hopefully this helps someone!

**Comment by srdjan** [comment] 2023-01-22 13:41
thanks for showing us your approach...
I have been working on this - expect a 'beta' release sometimes later today or tomorrow

**Comment by srdjan** [comment] 2023-01-22 17:01
so, this feature is now published here:
https://www.npmjs.com/package/react-multistep

It is beta, since it needs some testing.

Let me know

**Comment by srdjan** [comment] 2023-01-22 18:21
documentation is coming, but for now...

If the step (child form component) needs to deactivate 'Next' button based on validation, following changes are required:

<img width="500" alt="child-step-component-changes" src="https://user-images.githubusercontent.com/61190/213932636-5f2d8dfe-0f98-457e-9f0f-6a890174a834.png">

As you can see,  Multistep adds dynamically a new prop function to child components;

  `signalIfValid(valid: boolean)`

By default it is 'false; and child components invokes it based on current validation. I use a simple checkbox to simulate valid/not valid.

Also, for this feature, steps (child form components) are added inline:

<img width="500" alt="child-steps-added-to-multistep-inline" src="https://user-images.githubusercontent.com/61190/213932915-5c9301df-3d6c-4772-b697-be58e80a8851.png">

So, if somebody has time, please try it out and help testing... If anything is not working (I'm sure there will be some), please open issues and I'll figure it out...

**Comment by srdjan** [comment] 2023-01-25 11:49
closing... please open issues if you discover a problem or some aspect of this feature is missing

**Closed by srdjan** 2023-01-25 11:49 UTC
Labels: story

**Comment by dividor** [comment] 2023-01-26 03:35
Thanks Srdjan, much appreciated.
