### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by yarivShamash** [srdjan/react-multistep#54] opened 2019-11-25 09:32 UTC
Hey,

I'm trying to learn your repo using the example but encoutered problems with the last two steps.
On `react-multistep/example` when running `sudo npm run build:dev` I receive the following error:
```
npm ERR! missing script: build:dev
```
any thoughts on how and why can it happen?

**Comment by kashammari** [comment] 2019-12-01 19:40
It's in the package.json in the src folder!

**Comment by kashammari** [comment] 2019-12-01 20:18
I get this node module error so I gave up on it!
./src/node_modules/react/cjs/react.development.js
  Line 632:60:  Definition for rule 'react-internal/warning-and-invariant-args' was not found

**Comment by yarivShamash** [comment] 2019-12-02 08:17
Thanks, I'll look into it.

**Comment by srdjan** [comment] 2019-12-17 21:20
should be fixed now... on master - not on NPM yet

**Closed by srdjan** 2019-12-17 21:20 UTC

**Comment by nuritb** [comment] 2020-03-21 19:12
I love your repo! but I also get this error:

./src/node_modules/react/cjs/react.development.js
Line 632:60: Definition for rule 'react-internal/warning-and-invariant-args' was not found.

Is there any solution?

**Comment by srdjan** [comment] 2020-03-21 22:42
can't reproduce...
are you using the module from NPM or have cloned/forked the repo?
